# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.21

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/nic/Documents/Projects/RayTracerChallenge/test

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/nic/Documents/Projects/RayTracerChallenge

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/nic/Documents/Projects/RayTracerChallenge/CMakeFiles /home/nic/Documents/Projects/RayTracerChallenge//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/nic/Documents/Projects/RayTracerChallenge/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named UnitTests

# Build rule for target.
UnitTests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 UnitTests
.PHONY : UnitTests

# fast build rule for target.
UnitTests/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnitTests.dir/build.make CMakeFiles/UnitTests.dir/build
.PHONY : UnitTests/fast

# target to build an object file
CameraTest.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnitTests.dir/build.make CMakeFiles/UnitTests.dir/CameraTest.o
.PHONY : CameraTest.o

# target to preprocess a source file
CameraTest.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnitTests.dir/build.make CMakeFiles/UnitTests.dir/CameraTest.i
.PHONY : CameraTest.i

# target to generate assembly for a file
CameraTest.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnitTests.dir/build.make CMakeFiles/UnitTests.dir/CameraTest.s
.PHONY : CameraTest.s

# target to build an object file
CanvasTest.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnitTests.dir/build.make CMakeFiles/UnitTests.dir/CanvasTest.o
.PHONY : CanvasTest.o

# target to preprocess a source file
CanvasTest.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnitTests.dir/build.make CMakeFiles/UnitTests.dir/CanvasTest.i
.PHONY : CanvasTest.i

# target to generate assembly for a file
CanvasTest.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnitTests.dir/build.make CMakeFiles/UnitTests.dir/CanvasTest.s
.PHONY : CanvasTest.s

# target to build an object file
ColorTest.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnitTests.dir/build.make CMakeFiles/UnitTests.dir/ColorTest.o
.PHONY : ColorTest.o

# target to preprocess a source file
ColorTest.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnitTests.dir/build.make CMakeFiles/UnitTests.dir/ColorTest.i
.PHONY : ColorTest.i

# target to generate assembly for a file
ColorTest.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnitTests.dir/build.make CMakeFiles/UnitTests.dir/ColorTest.s
.PHONY : ColorTest.s

# target to build an object file
LightTest.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnitTests.dir/build.make CMakeFiles/UnitTests.dir/LightTest.o
.PHONY : LightTest.o

# target to preprocess a source file
LightTest.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnitTests.dir/build.make CMakeFiles/UnitTests.dir/LightTest.i
.PHONY : LightTest.i

# target to generate assembly for a file
LightTest.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnitTests.dir/build.make CMakeFiles/UnitTests.dir/LightTest.s
.PHONY : LightTest.s

# target to build an object file
MaterialTest.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnitTests.dir/build.make CMakeFiles/UnitTests.dir/MaterialTest.o
.PHONY : MaterialTest.o

# target to preprocess a source file
MaterialTest.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnitTests.dir/build.make CMakeFiles/UnitTests.dir/MaterialTest.i
.PHONY : MaterialTest.i

# target to generate assembly for a file
MaterialTest.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnitTests.dir/build.make CMakeFiles/UnitTests.dir/MaterialTest.s
.PHONY : MaterialTest.s

# target to build an object file
MatrixTest.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnitTests.dir/build.make CMakeFiles/UnitTests.dir/MatrixTest.o
.PHONY : MatrixTest.o

# target to preprocess a source file
MatrixTest.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnitTests.dir/build.make CMakeFiles/UnitTests.dir/MatrixTest.i
.PHONY : MatrixTest.i

# target to generate assembly for a file
MatrixTest.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnitTests.dir/build.make CMakeFiles/UnitTests.dir/MatrixTest.s
.PHONY : MatrixTest.s

# target to build an object file
RayTest.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnitTests.dir/build.make CMakeFiles/UnitTests.dir/RayTest.o
.PHONY : RayTest.o

# target to preprocess a source file
RayTest.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnitTests.dir/build.make CMakeFiles/UnitTests.dir/RayTest.i
.PHONY : RayTest.i

# target to generate assembly for a file
RayTest.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnitTests.dir/build.make CMakeFiles/UnitTests.dir/RayTest.s
.PHONY : RayTest.s

# target to build an object file
SphereTest.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnitTests.dir/build.make CMakeFiles/UnitTests.dir/SphereTest.o
.PHONY : SphereTest.o

# target to preprocess a source file
SphereTest.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnitTests.dir/build.make CMakeFiles/UnitTests.dir/SphereTest.i
.PHONY : SphereTest.i

# target to generate assembly for a file
SphereTest.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnitTests.dir/build.make CMakeFiles/UnitTests.dir/SphereTest.s
.PHONY : SphereTest.s

# target to build an object file
TransformationTest.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnitTests.dir/build.make CMakeFiles/UnitTests.dir/TransformationTest.o
.PHONY : TransformationTest.o

# target to preprocess a source file
TransformationTest.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnitTests.dir/build.make CMakeFiles/UnitTests.dir/TransformationTest.i
.PHONY : TransformationTest.i

# target to generate assembly for a file
TransformationTest.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnitTests.dir/build.make CMakeFiles/UnitTests.dir/TransformationTest.s
.PHONY : TransformationTest.s

# target to build an object file
TupleTest.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnitTests.dir/build.make CMakeFiles/UnitTests.dir/TupleTest.o
.PHONY : TupleTest.o

# target to preprocess a source file
TupleTest.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnitTests.dir/build.make CMakeFiles/UnitTests.dir/TupleTest.i
.PHONY : TupleTest.i

# target to generate assembly for a file
TupleTest.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnitTests.dir/build.make CMakeFiles/UnitTests.dir/TupleTest.s
.PHONY : TupleTest.s

# target to build an object file
WorldTest.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnitTests.dir/build.make CMakeFiles/UnitTests.dir/WorldTest.o
.PHONY : WorldTest.o

# target to preprocess a source file
WorldTest.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnitTests.dir/build.make CMakeFiles/UnitTests.dir/WorldTest.i
.PHONY : WorldTest.i

# target to generate assembly for a file
WorldTest.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnitTests.dir/build.make CMakeFiles/UnitTests.dir/WorldTest.s
.PHONY : WorldTest.s

# target to build an object file
main.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnitTests.dir/build.make CMakeFiles/UnitTests.dir/main.o
.PHONY : main.o

# target to preprocess a source file
main.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnitTests.dir/build.make CMakeFiles/UnitTests.dir/main.i
.PHONY : main.i

# target to generate assembly for a file
main.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnitTests.dir/build.make CMakeFiles/UnitTests.dir/main.s
.PHONY : main.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... UnitTests"
	@echo "... CameraTest.o"
	@echo "... CameraTest.i"
	@echo "... CameraTest.s"
	@echo "... CanvasTest.o"
	@echo "... CanvasTest.i"
	@echo "... CanvasTest.s"
	@echo "... ColorTest.o"
	@echo "... ColorTest.i"
	@echo "... ColorTest.s"
	@echo "... LightTest.o"
	@echo "... LightTest.i"
	@echo "... LightTest.s"
	@echo "... MaterialTest.o"
	@echo "... MaterialTest.i"
	@echo "... MaterialTest.s"
	@echo "... MatrixTest.o"
	@echo "... MatrixTest.i"
	@echo "... MatrixTest.s"
	@echo "... RayTest.o"
	@echo "... RayTest.i"
	@echo "... RayTest.s"
	@echo "... SphereTest.o"
	@echo "... SphereTest.i"
	@echo "... SphereTest.s"
	@echo "... TransformationTest.o"
	@echo "... TransformationTest.i"
	@echo "... TransformationTest.s"
	@echo "... TupleTest.o"
	@echo "... TupleTest.i"
	@echo "... TupleTest.s"
	@echo "... WorldTest.o"
	@echo "... WorldTest.i"
	@echo "... WorldTest.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

